import json,os,subprocess
exec(open('gen.py').read())
H2=json.load(open('h2.json')) if os.path.exists('h2.json') else {}
def flow(title,body,foot,w=660,close=None):
    cl='' if (close is False or (close is None and '取消' in foot)) else IB("x","关闭","icon round","style='border-color:transparent;background:var(--fill-2)'")
    return f'<div class="sheet m-float" style="position:relative;width:{w}px;max-width:100%;margin-bottom:40px"><div class="sh"><span class="st">{title}</span>{cl}</div>{body}<div class="sf">{foot}</div></div>'
def fld(l,inp,hint=''): return f'<div class="fl"><label>{l}</label>{inp}'+(f'<span class="t-note">{hint}</span>' if hint else '')+'</div>'
IN=lambda v='',ph='',cls='',st='':f'<input class="field {cls}" value="{v}" placeholder="{ph}" aria-label="{ph or v}" style="{st}">'
TA=lambda ph='',h=72,mono=True:f'<textarea class="field {"mono" if mono else ""}" style="height:{h}px;padding:8px 12px;width:100%" placeholder="{ph}"></textarea>'
def SUB(t): return f'<div class="t-section" style="margin:18px 0 10px">{t}</div>'
def ROW(*c,g=14,cols=None): return f'<div style="display:grid;grid-template-columns:{cols or " ".join(["1fr"]*len(c))};gap:{g}px;align-items:end">'+''.join(c)+'</div>'
def SLIDER(l,v,pct,disp): return f'<div style="display:flex;align-items:center;gap:12px"><span class="t-label" style="width:64px">{l}</span><div class="sl"><i style="width:{pct}%"></i><b style="left:calc({pct}% - 10px)"></b></div><span class="t-value num" style="width:44px;text-align:right">{disp}</span></div>'
def SWL(l,on=False,note=''): return f'<div style="display:flex;align-items:center;gap:10px">{SW(on,l)}<span class="t-body">{l}</span>'+(f'<span class="t-note">{note}</span>' if note else '')+'</div>'
def CARD(x,extra=''): return f'<div class="card" style="background:var(--fill);padding:16px;{extra}">{x}</div>'
def SEGX(items,on=0,st=''): return '<div class="seg" style="'+st+'">'+''.join(f'<button class="{"on" if i==on else ""}">{t}</button>' for i,t in enumerate(items))+'</div>'
def board(name,title,inner,cols=True,pad=40):
    h=H2.get(name,3000)
    body=f'<div class="dc wall" style="width:1440px;height:{h}px;position:relative;overflow:hidden"><div class="dim" style="background:rgba(20,30,45,.14)"></div><div class="flow-wrap" style="position:relative;padding:{pad}px">{inner}</div></div>'
    write(name,title,h,body);BOARDS[name]=h
def two(a,b): return f'<div style="display:grid;grid-template-columns:660px 660px;gap:40px;align-items:start;justify-content:center"><div>{a}</div><div>{b}</div></div>'
def wide(x,w=860): return f'<div style="display:flex;justify-content:center">{x}</div>'

# ---------- 自动化弹窗
def cond(v,op,val): return f'<div style="display:grid;grid-template-columns:1.4fr 110px 1fr 28px;gap:8px;align-items:center">{SELECT(v,200).replace("width:200px","width:100%")}{SELECT(op,110).replace("width:110px","width:100%")}{IN(val,"比较值")}{IB("x","移除","sm quiet")}</div>'
rule=flow('编辑规则',
 ROW(fld('规则 ID',IN('fixture-rule','唯一标识符')),fld('规则名称',IN('Fixture rule','规则显示名称')))
 +SUB('图标')+f'<div style="display:flex;align-items:center;gap:12px">{SEGX(["图标","图片"])}<div class="btn icon" style="width:40px;height:40px;font-size:20px">⚡</div><span class="t-note">输入 emoji，或选择图片（浏览 / 清除）</span></div>'
 +SUB('规则选项')+CARD(f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px 24px">{fld("条件逻辑",SELECT("AND",120))}{fld("冷却时间 (ms)",IN("1000","冷却时间","",""))}</div><div style="display:grid;gap:12px;margin-top:14px">{SWL("立即启用",True)}{SWL("显示在面板",True)}{SWL("允许手动触发",True)}</div>')
 +f'<div class="sec-h" style="margin-top:18px"><span class="t-section">触发条件</span><span style="display:flex;align-items:center;gap:14px">{SWL("仅手动触发",False)}{B("添加","plus","sm")}</span></div>'
 +CARD(cond('选择变量','==','')+'<div style="height:8px"></div>'+cond('cpu.avg_usage','>','80')+'<div class="t-note" style="margin-top:10px">点击「添加」创建触发条件，或勾选「仅手动触发」作为快捷动作。运算符：== · != · > · >= · < · <= · 变化 · 包含</div>')
 +f'<div class="sec-h" style="margin-top:18px"><span class="t-section">执行动作</span>{B("添加","plus","sm")}</div>'
 +CARD(f'<div style="display:grid;grid-template-columns:1fr 28px;gap:8px;align-items:center">{SELECT("Fixture action（日志）",200).replace("width:200px","width:100%")}{IB("x","移除","sm quiet")}</div><div class="t-note" style="margin-top:10px">从已创建的动作模板中选择要执行的动作；没有可选项时提示「请先在动作模板区域创建动作」。</div>'),
 B('取消','','lg')+B('保存修改','','lg primary'),w=860)
varsel=flow('选择触发条件变量',f'{IN("","搜索变量...","",'width:100%')}<div class="card" style="padding:0;margin-top:12px;background:var(--fill)"><div class="dis" style="font-size:13px"><span style="display:inline-block;transform:rotate(90deg);color:var(--ink-3)">›</span>系统变量</div>'+TR('1.4fr 1fr .8fr',['变量','当前值','类型'],True)+TR('1.4fr 1fr .8fr sel'.replace(' sel',''),['<span class="mono">cpu.avg_usage</span>','20','number'])+TR('1.4fr 1fr .8fr',['<span class="mono">fan.0.rpm</span>','1840','number'])+TR('1.4fr 1fr .8fr',['<span class="mono">agx.power</span>','off','string'])+'</div><div class="t-note" style="margin-top:8px">空状态：没有可用的变量 · 加载状态：加载变量列表…</div>',B('关闭','','lg primary'),w=660)
src=flow('添加外部数据源',
 SEGX(['REST API','WebSocket','Socket.IO','指令变量'],0,'display:flex')
 +'<div style="height:14px"></div>'+ROW(fld('数据源 ID',IN('','如: agx_temp')),fld('显示名称',IN('','如: AGX 温度')))
 +SUB('REST API 配置')+fld('请求地址',f'<div style="display:flex;gap:8px"><input class="field" style="flex:1" placeholder="http://…" aria-label="请求地址">{B("测试")}</div>')
 +'<div style="height:12px"></div>'+ROW(fld('方法',SELECT('GET',100)),fld('轮询间隔 (ms)',IN('1000','轮询间隔')),cols='100px 1fr')
 +'<div style="height:12px"></div>'+fld('Authorization 头（可选）',IN('','Bearer token'))
 +f'<div style="margin-top:14px" class="t-state">{ST("连接成功","ok")} <span class="t-note" style="margin-left:8px">原始数据 ▸</span></div>'
 +'<div class="t-label" style="margin:12px 0 6px">选择要提取的字段：</div><div style="display:flex;gap:6px;flex-wrap:wrap">'+''.join(B(x,'','sm') for x in ['data.temperature','data.fan','data.status'])+'</div>'
 +'<div style="height:12px"></div>'+fld('JSON 数据路径',IN('','如: data.temperature（留空取整个响应）'),'点击上方字段自动填入')
 +CARD('<div class="t-note" style="line-height:20px"><b style="color:var(--ink)">WebSocket</b>：地址 · 测试 · 路径 · 断线重连间隔<br><b style="color:var(--ink)">Socket.IO</b>：服务器地址 · 测试 · 事件名称（留空自动发现）· 超时 · 自动发现所有 JSON 字段（开关）<br><b style="color:var(--ink)">指令变量</b>：SSH 主机 · 指令 · 指令详情（命令/描述/超时）· 将监视的变量列表 · 检测间隔 (秒)</div>','margin-top:16px'),
 f'<span style="margin-right:auto;display:flex;align-items:center;gap:8px">{SW(True,"创建后立即启用")}<span class="t-body">创建后立即启用</span></span>'+B('取消','','lg')+B('添加数据源','','lg primary'))
tile=lambda t,d,on=False:f'<div class="tile{" on" if on else ""}" style="padding:12px 14px"><div><div class="t-body" style="font-weight:600">{t}</div><div class="t-note">{d}</div></div></div>'
act=flow('新建动作模板',
 f'<div class="t-section" style="margin-bottom:10px">选择动作类型</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">{tile("CLI 命令","执行本地控制台命令",True)}{tile("SSH 命令","执行已配置的 SSH 命令")}{tile("LED 控制","控制 LED 颜色和效果")}{tile("日志记录","输出日志消息")}{tile("设置变量","修改系统变量值")}{tile("Webhook","发送 HTTP 请求")}</div>'
 +SUB('配置参数（CLI 命令）')+fld('命令行',IN('','如: gpio --set 48 1','mono'),'支持所有控制台命令：gpio、device、fan、led、net 等')
 +'<div class="t-label" style="margin:10px 0 6px">快捷命令：</div><div style="display:flex;gap:6px;flex-wrap:wrap">'+''.join(B(x,'','sm') for x in ['GPIO','AGX 开机','AGX 重启','风扇','LED 动画'])+'</div>'
 +f'<div style="margin-top:12px" class="t-note">高级选项 ▸ 结果变量（如 cli.result）· 超时时间</div>'
 +SUB('基本信息')+ROW(fld('动作 ID',IN('','如: restart_agx'),'用于规则引用，只能包含字母、数字和下划线'),fld('显示名称',IN('','如: 重启 AGX'),'留空则使用 ID'))
 +'<div style="height:12px"></div>'+fld('描述',IN('','动作说明（可选）'))
 +f'<div style="display:grid;grid-template-columns:140px 1fr;gap:14px;margin-top:12px;align-items:end">{fld("执行延迟",IN("0","执行延迟"))}<div>{SWL("异步执行",False,"API 立即返回，动作在后台队列执行")}</div></div>'
 +CARD('<div class="t-note" style="line-height:20px">其他类型：SSH 命令（选择命令 + 命令详情）· LED 控制（设备 / 控制类型，矩阵屏另有文本、图像、QR、滤镜等）· 日志记录（级别 INFO/WARN/ERROR/DEBUG + 消息，支持 ${变量}）· 设置变量（变量名 + 值）· Webhook（URL、方法 POST/GET/PUT、请求体）</div>','margin-top:16px'),
 B('取消','','lg')+B('保存动作','','lg primary'))
vw=flow('变量：fixture-source','<div class="card" style="padding:0;background:var(--fill)">'+TR('1.4fr .8fr 1fr 1fr',['变量名','类型','当前值','更新时间'],True)+TR('1.4fr .8fr 1fr 1fr',['<span class="mono">fixture.temp</span>','number','42.0','17:16:55'])+TR('1.4fr .8fr 1fr 1fr',['<span class="mono">fixture.state</span>','string','ok','17:16:55'])+'</div><div class="t-note" style="margin-top:8px">空状态：该数据源暂无变量数据</div>',B('关闭','','lg primary'))
exp=lambda kind:flow(f'导出{kind}配置',fld('目标设备证书 (PEM)',TA('粘贴目标设备的证书。留空则使用本机证书（自加密）',96)),B('取消','','lg')+B('导出','dl','lg primary'),w=560)
imp=flow('导入数据源配置',f'<div class="t-label" style="margin-bottom:10px">选择 .tscfg 配置包文件以导入数据源</div><div style="display:flex;align-items:center;gap:12px">{B("选择文件","ul")}<span class="t-note">未选择任何文件</span></div>'+SUB('配置包内容')+'<div class="card" style="background:var(--fill);padding:8px 16px">'+KV('配置 ID','<span class="mono">agx_temp</span>')+KV('类型','数据源')+KV('签名者',ST('官方','ok'))+KV('备注','重启后自动加载')+'</div>'+f'<div style="margin-top:12px;display:grid;gap:8px">{ST("签名验证通过","ok")}{SWL("覆盖已存在的配置",False,"该配置已存在，导入将覆盖现有文件")}</div>',B('取消','','lg')+B('确认导入','','lg primary'),w=560)
board('SheetsAuto','自动化弹窗 目标稿',wide(rule,860)+two(varsel+src+vw,act+exp('数据源')+imp))

# ---------- LED / 网络 / 日志 / 文件 / 登录
eff=lambda n,on=False:f'<div class="tile{" on" if on else ""}" style="padding:10px 12px;justify-content:center"><span class="t-body">{n}</span></div>'
ledtabs=SEGX(['程序动画','图像/QR码','文本显示','后处理滤镜','色彩校正'],0,'display:flex;margin-bottom:16px')
led1=flow('LED 设置 · Board',ledtabs+'<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px">'+''.join(eff(x,i==1) for i,x in enumerate(['彩虹','火焰','呼吸','流星','波浪','闪烁','渐变','雨滴']))+'</div>'+SUB('设置')+f'<div class="t-note" style="margin-bottom:10px">当前：<b style="color:var(--ink)">火焰</b>（未选择动画时提示「请先选择一个动画」）</div>'+SLIDER('速度',5,50,'50')+f'<div style="display:flex;align-items:center;gap:12px;margin-top:14px"><span class="t-label" style="width:64px">颜色</span><span class="dotc" style="background:#ff6600;width:28px;height:28px"></span></div>',B('停止','stop','lg')+B('重置','','lg')+B('保存','','lg primary'),close=True)
cc=flow('全局色彩校正',f'{SWL("启用全局色彩校正",True)}'+SUB('白平衡 (RGB 缩放)')+f'<div class="t-note" style="margin-bottom:8px">独立调整 RGB 通道修正色温。默认 1.0，&lt;1.0 减少该通道，&gt;1.0 增强</div><div style="display:grid;gap:10px">{SLIDER("R",1,50,"1.00")}{SLIDER("G",1,50,"1.00")}{SLIDER("B",1,50,"1.00")}</div>'+SUB('Gamma 校正')+SLIDER('数值',1,40,'1.00')+SUB('亮度')+SLIDER('系数',1,50,'1.00')+SUB('饱和度')+SLIDER('系数',1,50,'1.00'),B('重置','','lg')+B('导出到 SD 卡','','lg')+B('从 SD 卡导入','','lg')+B('保存','','lg primary'),close=True)
img=flow('LED 设置 · Matrix',SEGX(['程序动画','图像/QR码','文本显示','后处理滤镜','色彩校正'],1,'display:flex;margin-bottom:16px')+SUB('图像').replace('margin:18px 0 10px','margin:0 0 10px')+f'<div style="display:flex;gap:8px">{IN("","/sdcard/images/...","","flex:1")}{B("浏览")}</div><div style="margin:10px 0">{SWL("居中显示",True)}</div>{B("显示图像","","primary")}'+SUB('QR 码')+fld('内容',IN('','输入文本或URL'))+'<div style="height:12px"></div>'+ROW(fld('纠错',SELECT('M - 15%',140)),fld('前景色','<span class="dotc" style="width:34px;height:34px;background:#000"></span>'),cols='1fr 1fr')+'<div style="height:12px"></div>'+fld('背景图',f'<div style="display:flex;gap:8px">{IN("","无","","flex:1")}{B("浏览")}{B("清除")}</div>')+f'<div style="margin-top:14px">{B("生成 QR 码","","primary")}</div>',B('关闭','','lg primary'),close=True)
txt=flow('LED 设置 · 文本显示',SEGX(['程序动画','图像/QR码','文本显示','后处理滤镜','色彩校正'],2,'display:flex;margin-bottom:16px')+fld('文本',IN('','输入要显示的文本'))+SUB('字体与样式')+ROW(fld('字体',SELECT('默认',160)+' '),fld('对齐',SELECT('居中',120)),fld('颜色','<span class="dotc" style="width:34px;height:34px;background:#fff"></span>'),cols='1fr 1fr 60px')+f'<div style="margin-top:8px">{B("刷新字体","refresh","sm quiet")}</div>'+SUB('位置')+f'<div style="display:flex;gap:8px;align-items:center">X {IN("0","X","","width:80px")} Y {IN("0","Y","","width:80px")} <span style="margin-left:8px">{SWL("自动位置",True)}</span></div>'+SUB('滚动')+f'<div style="display:flex;gap:12px;align-items:center">{SELECT("无",100)}<span class="t-label">速度</span>{IN("50","速度","","width:80px")}{SWL("循环滚动",False)}</div>',B('停止','stop','lg')+B('显示','','lg primary'),close=True)
flt=flow('LED 设置 · 后处理滤镜',SEGX(['程序动画','图像/QR码','文本显示','后处理滤镜','色彩校正'],3,'display:flex;margin-bottom:16px')+'<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px">'+''.join(eff(x,i==2) for i,x in enumerate(['脉冲','呼吸','闪烁','波浪','扫描线','故障艺术','彩虹','闪耀','等离子体','怀旧','色阶分离','对比度','反色','灰度']))+'</div>'+SUB('设置')+f'<div class="t-note">当前：<b style="color:var(--ink)">闪烁</b>（未选择时提示「请先选择一个滤镜」）· 参数随滤镜变化</div>',B('停止','stop','lg')+B('应用','','lg primary'),close=True)
scan=flow('WiFi 扫描','<div class="card" style="padding:0;background:var(--fill)">'+TR('1fr 90px 80px',[ '<span>Office-5G <span class="tag" style="margin-left:6px">WPA2</span></span>','<span class="state ok">-48 dBm</span>',ACT(B('连接','','sm'))])+TR('1fr 90px 80px',['隐藏网络','<span class="state">-71 dBm</span>',ACT(B('连接','','sm'))])+'</div><div class="t-note" style="margin-top:8px">空 / 加载：未发现网络 · 扫描中… · 需要切换到 STA 或 APSTA 模式</div>',B('刷新','refresh','lg')+B('关闭','','lg primary'),w=560)
wpw=flow('连接 Office-5G',fld('密码',IN('','输入 WiFi 密码','','width:100%'),'替代原生 prompt()'),B('取消','','lg')+B('连接','','lg primary'),w=480)
ap=flow('WiFi 热点配置',ROW(fld('SSID',IN('TianshanOS','SSID')),fld('密码',IN('','至少 8 位')))+'<div style="height:12px"></div>'+ROW(fld('信道',SELECT('1',100)),f'<div style="padding-bottom:6px">{SWL("隐藏 SSID",False)}</div>',cols='120px 1fr'),B('取消','','lg')+B('应用','','lg primary'),w=560)
aps=flow('热点接入设备','<div class="card" style="padding:0;background:var(--fill)">'+TR('1.2fr 1fr .6fr',['MAC','IP','RSSI'],True)+f'<div class="tr" style="--cols:1fr;color:var(--ink-3)">无接入设备</div></div>',B('关闭','','lg primary'),w=560)
dhcp=flow('DHCP 客户端',f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:12px"><span class="t-label">接口</span>{SELECT("WiFi AP",140)}{IB("refresh","刷新")}</div><div class="card" style="padding:0;background:var(--fill)">'+TR('1.2fr 1fr 1fr',['MAC','IP','主机名'],True)+f'<div class="tr" style="--cols:1fr;color:var(--ink-3)">暂无客户端</div></div>',B('关闭','','lg primary'),w=560)
lg=lambda t,c,m:f'<div style="display:grid;grid-template-columns:70px 50px 100px 1fr;gap:8px;color:{c}"><span>{t}</span><span>{m[0]}</span><span>{m[1]}</span><span>{m[2]}</span></div>'
logs=flow('系统日志',f'<div style="display:flex;gap:8px;align-items:center;margin-bottom:12px">{SELECT("全部",100)}{IN("","过滤TAG...","","width:150px")}{IN("","搜索日志...","","flex:1")}<span style="display:flex;gap:6px;align-items:center;margin-left:8px">{SW(True,"自动滚动")}<span class="t-label">自动滚动</span></span></div><div class="term" style="height:200px;font-size:12px;line-height:18px">'+lg('17:16:01','#8ee59a',['I','http','GET /api/v1/device/ping 200'])+lg('17:16:03','#8ee59a',['I','fan','fan0 auto 40%'])+lg('17:16:07','#ffd98a',['W','power','input 19.2 V'])+lg('17:16:09','#ff9f9a',['E','ota','server unreachable'])+'</div>',B('刷新日志','refresh','lg')+B('清空日志','','lg')+B('关闭','','lg primary'),w=760,close=False)
pick=flow('选择图片',f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:12px">{IB("home","根目录")}<span class="t-note">/</span><span class="t-body">sdcard</span><span class="t-note">/</span><span class="t-body" style="font-weight:600">images</span></div><div class="card" style="padding:0;background:var(--fill)">'+TR('24px 1fr 90px',[IC["folder"],'icons','-'])+TR('24px 1fr 90px',[IC["doc"],'logo.png','13 KB'])+'</div><div class="t-note" style="margin-top:8px">空 / 缺失：无图片文件 · 目录不存在（{}）</div>'.replace('{}',f'提供「创建目录」按钮'),B('取消','','lg'),w=560)
login=flow('登录 TianshanOS',ROW(fld('用户名',IN('admin','用户名')),cols='1fr')+'<div style="height:12px"></div>'+fld('密码',IN('','请输入密码','','width:100%'))+f'<div style="margin-top:10px">{ST("用户名或密码错误","bad")}</div>',B('取消','','lg')+B('登录','','lg primary'),w=420)
board('SheetsLed','LED · 网络 · 日志 · 登录 弹窗 目标稿',two(led1+cc+txt+login+logs,img+flt+scan+wpw+ap+aps+dhcp+pick))

# ---------- 安全弹窗
csr=flow('生成证书签名请求',ROW(fld('设备 ID',IN('TIANSHAN-RM01-0001','设备 ID')),fld('组织',IN('HiddenPeak Labs','组织')),fld('部门',IN('Device','部门')),cols='1.4fr 1fr 1fr')+'<div style="height:12px"></div>'+fld('CSR (PEM)',TA('生成后显示在此',90)),B('复制到剪贴板','cpy','lg')+B('关闭','','lg')+B('生成证书签名请求','','lg primary'),w=660,close=False)
ic_=lambda t,ph,ro=False:flow(t,TA(ph,120),B('取消','','lg')+B('安装','','lg primary'),w=560)
certv=flow('查看证书',TA('-----BEGIN CERTIFICATE-----',140),B('复制到剪贴板','cpy','lg')+B('关闭','','lg primary'),w=560,close=False)
ckp=flow('生成密钥对',f'<div class="t-note">用于 HTTPS 服务器证书的密钥对。生成后可继续「生成 CSR」。</div>',B('取消','','lg')+B('生成','','lg primary'),w=460)
pimp=flow('导入配置包',f'<div style="display:flex;align-items:center;gap:12px;margin-bottom:12px">{B("选择文件","ul")}<span class="t-note">未选择任何文件</span></div>'+fld('配置包内容',TA('{"tscfg_version":"…',96)),B('取消','','lg')+B('仅验证','','lg')+B('导入','','lg primary'),w=560)
pexp=flow('导出配置包',f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:10px">{IN("/sdcard","当前目录","mono","flex:1")}{B("上级目录","","sm")}{IB("refresh","刷新")}</div><div class="card" style="padding:0;background:var(--fill)">'+TR('24px 1fr',['<span class="chk on"></span>','led/effects.json'])+TR('24px 1fr',['<span class="chk"></span>','led/text.json'])+f'</div><div style="display:flex;gap:8px;margin:10px 0">{B("全选","","sm")}{B("取消全选","","sm")}{B("选择整个目录","","sm")}</div>'+ROW(fld('名称',IN('','自动从文件名获取')),fld('描述',IN('','LED 特效配置')))+'<div style="height:12px"></div>'+fld('接收方设备证书',TA('-----BEGIN CERTIFICATE-----',72))+'<div style="height:12px"></div>'+fld('配置包 (.tscfg)',TA('配置包将在此显示...',72)),B('复制到剪贴板','cpy','lg')+B('下载到本地','dl','lg')+B('取消','','lg')+B('生成配置包','','lg primary'),w=760,close=False)
plist=flow('配置包列表',f'<div style="display:flex;gap:8px;margin-bottom:12px">{IN("/sdcard/packs","路径","mono","flex:1")}{IB("refresh","刷新")}</div><div class="card" style="padding:0;background:var(--fill)"><div class="tr" style="--cols:1fr;color:var(--ink-3)">暂无配置包</div></div>',B('关闭','','lg primary'),w=560)
rev=flow('撤销公钥',ROW(fld('主机',IN('','192.168.55.100 或 hostname')),fld('用户名',IN('root','用户名')),fld('端口',IN('22','端口')),cols='1.6fr 1fr 80px')+'<div style="height:12px"></div>'+fld('SSH 登录密码',IN('','输入 SSH 登录密码','','width:100%')),B('取消','','lg')+B('撤销公钥','','lg primary','style="background:var(--bad);border-color:var(--bad)"'),w=620)
mis=flow('主机指纹不匹配',f'<div style="display:flex;gap:8px;align-items:flex-start;color:var(--warn)">{IC["warn"]}<span class="t-body" style="color:var(--ink)">该主机的指纹与已记录的不一致。可能是服务器重装，也可能存在中间人攻击。</span></div><div style="height:12px"></div>'+fld('主机',IN('192.0.2.30','主机','mono'))+'<div style="height:12px"></div>'+fld('已记录指纹',IN('SHA256:aB…','指纹','mono'))+'<div style="height:12px"></div>'+fld('当前指纹',IN('SHA256:xY…','指纹','mono')),B('取消','','lg')+B('更新主机密钥','','lg primary','style="background:var(--bad);border-color:var(--bad)"'),w=560)
imph=flow('导入主机',f'<div class="t-note">Pattern B 表单：主机地址、端口、用户名、部署密钥（字段以现有页面为准，此处仅表示样式）。</div>',B('取消','','lg')+B('导入','','lg primary'),w=460)
board('SheetsSec','安全页弹窗 目标稿',two(csr+ic_('安装证书','-----BEGIN CERTIFICATE-----')+ic_('安装 CA','-----BEGIN CERTIFICATE-----')+certv+ckp,pexp+pimp+plist+rev+mis+imph))

# ---------- 状态与菜单
lang=f'<div class="m-float" style="border-radius:16px;padding:6px;width:180px"><div style="height:32px;border-radius:10px;padding:0 10px;display:flex;align-items:center;gap:8px;">✓ 中文</div><div style="height:32px;border-radius:10px;padding:0 10px;display:flex;align-items:center;gap:8px;padding-left:28px;background:var(--accent-text);color:#fff">English <span style="margin-left:auto;font-size:12px;opacity:.8">悬停</span></div></div>'
toast=lambda k,t:f'<div class="m-float" style="border-radius:16px;padding:12px 16px;display:flex;align-items:center;gap:10px;width:max-content;margin-bottom:10px"><span class="dot {k}"></span><span class="t-body">{t}</span></div>'
alertx=flow('确认删除 fixture-key？',f'<div class="t-body" style="color:var(--ink-2)">此操作无法撤销。替代原生 confirm() / alert()。</div>',B('取消','','lg')+B('删除','','lg primary','style="background:var(--bad);border-color:var(--bad)"'),w=420)
demo=f'''<div class="card" style="background:rgba(255,255,255,.72);padding:0;overflow:hidden">{TR('1fr 120px',['默认行','值'])}<div class="tr hov" style="--cols:1fr 120px"><div>悬停行</div><div>值</div></div><div class="tr rsel" style="--cols:1fr 120px"><div>选中行</div><div>值</div></div></div>
<div style="display:flex;gap:10px;margin-top:14px;align-items:center"><button class="btn">默认</button><button class="btn" style="background:var(--fill-2)">按下</button><button class="btn" style="box-shadow:0 0 0 3px rgba(0,122,255,.38)">焦点</button><button class="btn" disabled style="opacity:.4">禁用</button><span style="display:inline-block;width:16px;height:16px;border-radius:50%;border:2px solid var(--fill-2);border-top-color:var(--accent-text)"></span><span class="t-note">加载中</span></div>'''
stw=f'''<div class="sheet m-float" style="position:relative;width:660px;padding:24px;margin-bottom:40px"><div class="st" style="font-size:20px;margin-bottom:14px">菜单 · 提示 · 状态</div><div class="t-note" style="margin-bottom:8px">语言菜单（模式 D）</div>{lang}<div class="t-note" style="margin:18px 0 8px">Toast（成功 / 信息 / 警告 / 错误）</div>{toast("ok","已保存关机设置")}{toast("","正在连接…")}{toast("warn","输入电压过低：11.8 V")}{toast("bad","保存失败：设备无响应")}<div class="t-note" style="margin:18px 0 8px">列表与控件状态</div>{demo}</div>'''
board('SheetsStates','菜单、提示与状态 目标稿',two(stw,alertx+f'<div class="sheet m-float" style="position:relative;width:660px;padding:24px"><div class="st" style="font-size:20px;margin-bottom:10px">原生对话框清单</div><div class="t-body" style="color:var(--ink-2);line-height:22px">现有 app.js 里有 1 处 <span class="mono">prompt()</span>（WiFi 密码）、1 处 <span class="mono">confirm()</span>（指纹确认）、15 处 <span class="mono">alert()</span>。它们会打断页面、样式无法控制，落地时全部换成上面的模式 A / B 弹窗。</div></div>'))

# ---------- canvas
c=json.load(open(P+'canvas.json'))
extra=[('SheetsAuto','自动化弹窗 目标稿',(0,6560)),('SheetsLed','LED · 网络 · 日志 · 登录 弹窗 目标稿',(1520,6560)),('SheetsSec','安全页弹窗 目标稿',(3040,6560)),('SheetsStates','菜单、提示与状态 目标稿',(0,10100))]
for k,t,(x,y) in extra:
    c['boards'][k+'.dc.html']={'x':x,'y':y,'w':1440,'h':BOARDS[k],'title':t}
    if k+'.dc.html' not in c['order']: c['order'].append(k+'.dc.html')
json.dump(c,open(P+'canvas.json','w'),ensure_ascii=False,indent=1)
