// Final built assets, real xterm renderer, and Chromium media fallback evidence.
// All network ends at the local fixture. No device writes.
const fs=require('node:fs');const{chromium}=require('/Users/massif/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='output/macos27-20260928';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const rows=[];try{for(const label of ['A','B']){const page=await browser.newPage({viewport:{width:1440,height:1000}});const origin='http://127.0.0.1:'+(label==='A'?18784:18785);const errors=[];page.on('pageerror',e=>errors.push(String(e)));
for(const width of [1440,320])for(const route of ['/','/network','/files','/terminal','/automation','/commands','/security','/ota']){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(origin+'/?state=populated&lang=en-US#'+route);await page.waitForTimeout(700);rows.push({name:'built-route',label,route,width,...await page.evaluate(()=>({innerWidth,topContentVisible:document.querySelector('#page-content').getBoundingClientRect().top>=document.querySelector('.header').getBoundingClientRect().bottom,overflow:document.documentElement.scrollWidth>innerWidth,inputs:[...document.querySelectorAll('input,select,textarea,button')].filter(e=>e.getClientRects().length).length,bodyText:document.querySelector('main').innerText.slice(0,100)}))});await page.screenshot({path:out+'/after/built-'+label+'-'+(route.slice(1)||'system')+'-'+width+'.png'});}
await page.setViewportSize({width:1440,height:1000});await page.goto(origin+'/?state=populated#/terminal');await page.locator('.xterm-helper-textarea').waitFor();await page.waitForTimeout(200);await page.evaluate(()=>webTerminal.ws.emit({type:'output',data:'\r\n\u001b[31mANSI_RED_SAMPLE\u001b[0m PLAIN_SAMPLE\r\n'}));await page.waitForTimeout(200);
rows.push({name:'terminal-ansi-selection',label,...await page.evaluate(()=>{const term=webTerminal.terminal,buf=term.buffer.active;let row=-1;for(let i=0;i<buf.length;i++)if(buf.getLine(i).translateToString().includes('ANSI_RED_SAMPLE'))row=i;if(row<0)throw Error('ANSI sample missing');const line=buf.getLine(row);term.select(0,row,15);const red=line.getCell(0),plain=line.getCell(16);return{selected:term.getSelection(),row,line:line.translateToString(),red:{color:red.getFgColor(),palette:red.isFgPalette()},plain:{color:plain.getFgColor(),default:plain.isFgDefault()},theme:term.options.theme,method:'Synthetic bytes delivered through fixture WebSocket to original xterm; selection through xterm public API, not physical clipboard/IME'};})});await page.screenshot({path:out+'/after/terminal-ansi-'+label+'.png'});
if(label==='B'){await page.goto(origin+'/?state=populated#/');await page.locator('[onclick="showMemoryDetailModal()"]').click();const cdp=await page.context().newCDPSession(page);for(const[feature,value]of[['prefers-reduced-transparency','reduce'],['prefers-contrast','more'],['forced-colors','active'],['prefers-reduced-motion','reduce']]){await cdp.send('Emulation.setEmulatedMedia',{features:[{name:feature,value}]});await page.waitForTimeout(100);rows.push({name:'media-fallback',feature,value,...await page.evaluate(({feature,value})=>{const e=document.querySelector('#memory-detail-modal .modal-content'),s=getComputedStyle(e);return{matches:matchMedia('('+feature+': '+value+')').matches,background:s.background,filter:s.backdropFilter,animation:s.animation,transition:s.transition};},{feature,value})});await page.screenshot({path:out+'/after/fallback-'+feature+'.png'});}await cdp.send('Emulation.setEmulatedMedia',{features:[]});}
if(label==='B'&&rows.some(r=>r.label==='B'&&r.name==='built-route'&&(!r.topContentVisible||r.overflow)))throw Error('Built layout clips or overflows content');
rows.push({name:'page-errors',label,errors});await page.close();}}finally{fs.writeFileSync(out+'/final-browser.json',JSON.stringify(rows,null,2));await browser.close();}})();
